server:
  port: 8000
  servlet:
    contextPath: /
management:
  endpoints:
    web:
      base-path: /v1/fd/actuator
      exposure:
        include: health,info,loggers,metrics
swagger:
  enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    com.myorg: INFO
  pattern:
    #console: '%d{yyyy-MM-dd HH:mm:ss.SSS} | marker=%marker |  clientId=%X{clientId} | level=%5p | thread=%thread | traceId=%X{traceId} spanId=%X{spanId} |  projectVersion=%X{projectVersion} |class=%class{15}.%L | msg="%.-50000m"%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} |level=%5p |class=%class{15}.%L | msg="%.-50000m"%n'

spring:
  application:
    name: "example-ha-sdk17"
  datasource:
    url: jdbc:postgresql://192.168.200.156/test
    username: transversales
    password: transversales
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
        jdbc:
          time_zone: UTC
my-vars:
  clientId: "some-micro"
  projectVersion: "1.0.0"
  traceId: "traceId"
  spanId: "spanId"
  log: "something"